collections:
  - name: 'projects-fr' # Used in routes, e.g., /admin/collections/blog
    label: 'Projets' # Used in the UI
    folder: 'src/content/projects/fr' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - label: 'Titre'
        name: 'title'
        widget: 'string'
      - label: 'Image'
        name: 'image'
        widget: 'image'
      - label: 'Liens'
        name: 'links'
        summary: '{{fields.type}}:{{fields.url}}'
        widget: 'list'
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'select'
            options:
              - label: 'Lien vers le site'
                value: 'url'
              - label: 'Lien vers le code'
                value: 'code'
              - label: 'Lien la page plus dinfo'
                value: 'more'
          - label: 'URL'
            name: 'url'
            widget: 'string'
      - label: 'Technologies'
        name: 'technologies'
        widget: 'list'

      - label: 'Body'
        name: 'body'
        widget: 'markdown'

media_folder: 'src/img'
public_folder: 'src/img'

backend:
  name: github
  repo: LaurentPCaron/porfolio # Path to your GitHub repository
